---
{{- if .Values.persistence.data.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "unifi.fullname" . }}-data
  labels:
    {{- include "unifi.labels" . | nindent 4 }}
  {{- with .Values.persistence.data.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.data.accessMode | default "ReadWriteOnce" | quote }}
  storageClassName: {{ .Values.persistence.data.storageClass | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size | quote }}
{{- end }}