---
apiVersion: v2
name: unifi
description: UniFi Network Controller Helm Chart
type: application
version: 0.1.0
appVersion: "7.1.68"
keywords:
  - unifi
  - ubiquiti
  - networking
  - controller
home: https://www.ui.com/
sources:
  - https://github.com/k8s-at-home/charts
maintainers:
  - name: wauhost
    email: admin@wauhost.com